name: Deploy React App #Workflow name

on:
  workflow_dispatch:
  push:
    branches:
      - main #trigger this workflow

jobs:
  build-and-deploy-react:
    runs-on: ubuntu-latest

    steps:
      #checkout to repository
      - name: Checkout code
        uses: actions/checkout@v4

      #setup node.js
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-versions: 18

      #install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      #Build project
      - name: Build React App
        run: npm run build
        working-directory: ./client

        env:
          VITE_API_URL: ${{secrets.VITE_API_URL}}
          VITE_GOOGLE_CLIENT_ID: ${{secrets.VITE_GOOGLE_CLIENT_ID}}

    deploy:
      name: Deploy Frontend to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        branch: gh-pages
        github_token: ${{ secrets.Token }}
        publish_dir: ./client/dist
